USE blocknote;

CREATE TABLE IF NOT EXISTS Users(
    id INT NOT NULL AUTO_INCREMENT,
    username VARCHAR(45) NOT NULL UNIQUE,
  	email VARCHAR(45) NOT NULL UNIQUE,
    password VARCHAR(94) NOT NULL,
    created_date DATETIME NOT NULL,
    PRIMARY KEY(id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
